namespace SoundCloud.API.Client.Objects.ExplorePieces
{
    public enum SCExploreCategoryType
    {
        PopularMusic,
        AlternativeRock,
        Ambient,
        Classical,
        Country,
        DanceAndEDM,
        Dancehall,
        DeepHouse,
        Disco,
        DrumAndBass,
        Dubstep,
        Electronic,
        FolkAndSingerSongwriter,
        HipHopAndRap,
        House,
        Indie,
        JazzAndBlues,
        Latin,
        Metal,
        Piano,
        Pop,
        RnBAndSoul,
        Reggae,
        Reggaeton,
        Rock,
        Soundtrack,
        Techno,
        Trance,
        Trap,
        Triphop,
        World
    }
}